# Generated by Django 4.2.9 on 2024-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Clothes', 'Clothes'), ('Weapons', 'Weapons'), ('Objects', 'Objects'), ('Extras', 'Extras')], max_length=7),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
